### ISSUE TITLE
Not working on 64-bit devices:

### ISSUE THREAD

**Issue by Ghost-chu** [spotsnel/tailscaled-android#3]
### What is the issue?
```
~/tailscale $ ./tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055 --socket /data/data/com.termux/files/usr/run/tailscaled.sock --statedir /data/data/com.termux/files/home/.config/tailscale/
error: "/data/data/com.termux/files/home/tailscale/tailscaled" is 32-bit instead of 64-bit
~/tailscale $ ./tailscale
error: "/data/data/com.termux/files/home/tailscale/tailscale" is 32-bit instead of 64-bit         ~/tailscale $
```

### Steps to reproduce

run tailscaled in termux

### OS

Android

### OS version

ColorOS 14.0 / Android 14

### Tailscale version

Android build 1.73.113-t787d121bf

### Other software

Termux

### Bug report

not working at all

**Comment by gbraad** [comment]
weird. this should have been compiled as aarch64. binary was tested on several devices: anbernic, samsung, etc but perhaps a build error. Will check on an oppo device I have and otherwise rebuild.

**Comment by gbraad** [comment]
Hmmm... `GOARCH=arm64` is not correctly picked up;

```
ELF 32-bit LSB executable, ARM, EABI5 version 1 
```

Will force build this on an Ampere Altra instead, as I suspect the cross-compilation failed.

**Comment by gbraad** [comment]
@Ghost-chu published arm64 builds on: https://github.com/spotsnel/tailscaled-android/releases/tag/1.74.2

```
ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, 
```

Please have a look. Have not tested them myself yet as there is a holiday

**Comment by gbraad** [comment]
just tested this version on the go. works as expected.
Closing for now. If it still has an issue, please re-open or create a new issue.
